### ISSUE TITLE
Prevent saving movie twice 

### ISSUE THREAD

**Issue by offa** [ben-hx/trashbay#13]
Pressing *Save* twice while adding a movie shouldn't be possible. Either redirect to the movie overview after a (successfully) adding or show the just added movie with disabled edit controls.

### Reproduction

1. Add a new Movie
1. Press `Save` twice
1. An error is shown; `Save` still possible

### Error

> insertDocument :: caused by :: 11000 E11000 duplicate key error index: trashbay.movies.$title_1 dup key: { : "The Toxic Avenger Part III: The Last Temptation of Toxie" }

**Comment by offa** [comment]
The movie is (correctly) added only once btw.

**Comment by ben-hx** [comment]
Yo, fixed it. when saving successfully the input fields will be empty again!
