### ISSUE TITLE
wrong movie limit after first page

### ISSUE THREAD

**Issue by Sydrimon** [ben-hx/trashbay#19]
the correct number of movies is shown on the first page, but not on the other pages

**Comment by ben-hx** [comment]
can you show me some screenshot's. for me it's working!

**Comment by Sydrimon** [comment]
![image](https://cloud.githubusercontent.com/assets/15202669/25071731/131e4410-22bf-11e7-84b6-8c697db21814.png)

**Comment by Sydrimon** [comment]
![image](https://cloud.githubusercontent.com/assets/15202669/25071746/44fe74d2-22bf-11e7-83cd-a8bfa9d78cbb.png)

**Comment by ben-hx** [comment]
Ahhhh thx! fixed it ;)
